### PR TITLE
feat: add diagrams to platform overview

### PR DESCRIPTION
**Pull request by avneesh0612**

### CODE REVIEW

**Comment by ciaranightingale** [comment]
Not viewing the light mode version when I am on light mode? 
image

**Comment by avneesh0612** [comment]
Not yet sure how to do that in docs so currently shipping it with dark mode only but have added light mode versions for later use

**Comment by ciaranightingale** [comment]
https://docusaurus.io/docs/styling-layout#dark-mode 

You can wrap in a div and set the visibility in CSS based on the theme - the classes are handled by Docusaurus

**Comment by ciaranightingale** [comment]
This page is also helpful https://docusaurus-i18n-staging.netlify.app/ja/docs/markdown-features/assets

**Comment by ciaranightingale** [comment]
Will do this now so we can ship if that's cool

**Comment by ciaranightingale** [comment]
https://github.com/thirdweb-dev/docs/pull/648

**Comment by ciaranightingale** [comment]
https://github.com/thirdweb-dev/docs/pull/647

**Pull request merged**
