### PR TITLE
Update docs to clarify that you cannot implement useBuyNow hook on MarketplaceV3

### PR DESCRIPTION
**Pull request by mykcryptodev**

### CODE REVIEW

**Comment by jarrodwatts** [comment]
Thanks Myk!

**Comment by jarrodwatts** [comment]
Looks like we have a contribution for this - https://github.com/thirdweb-dev/js/pull/993

Let's wait for that to be merged and update to link to this 😁

**Comment by mykcryptodev** [comment]
Oh heck yeah - even better!

**Comment by saminacodes** [comment]
@mykcryptodev was this ever followed up on?

**Comment by mykcryptodev** [comment]
> @mykcryptodev was this ever followed up on?
@saminacodes i took a look at the linkedpr and it looks like it will implement a new hook instead of making useBuyNow() marketplaceV3 compatible so I think this docs PR is still relevant

**Pull request merged**
