### PR TITLE
Jw/re structure docs

### PR DESCRIPTION
**Pull request by jarrodwatts**

### CODE REVIEW

**Comment by jarrodwatts** [comment]
there is a todo, fixing

**Comment by jarrodwatts** [comment]
fixed todo

**Comment by jnsdls** [comment]
@jarrodwatts can we start the sidebar open like this: 
image

**Comment by adam-maj** [comment]
Screen Shot 2022-05-28 at 6 21 43 PM
Now installation isnt on sidebar or frontpage? We should definitely have it somewhere obvious

**Comment by jnsdls** [comment]
when colormode is ['dark'] can we use css `filter: invert(1)` on the solidity icon?

image
becomes
image

by doing that

**Comment by jnsdls** [comment]
this is better than what we have currently so we'll ship it and improve from there

**Pull request merged**
